### ISSUE TITLE
Network Throttling

### ISSUE THREAD

**Issue by rderewianko** [brysontyrrell/ODST#5]
Hi Bryson!

Currently our solution for syncing has network throttling, defined by two things: Time of day and speed. 

Eg: local time boston can only download and upload 1500kb/s during the day.  After hours, throttle limits do not exist.
Tokyo, also is restricted local time, and after hours.

This could also be used as a 1 kb/s upload for sites that are download only.

**Comment by Hacksore** [comment]
@rderewianko It's my understanding that the webapp will not be responsible for serving payloads to clients so throttling can be done on whatever web server you use.

Here is some info on setting up network rate limiting on nginx.
https://www.nginx.com/blog/rate-limiting-nginx/

@brysontyrrell Am I correct in saying this?

**Comment by brysontyrrell** [comment]
So far I've been setting limits in the web server when enforcing that.

There is a `/share/` endpoint defined for the application to serve files, but the optimal configuration would be to alias the share directory in the web server configuration and let that handle the file requests.
